version: '3.8'

services:
  llm-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: llm-server-template-1
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - MODEL_DIR=/app/models
      - DEFAULT_MODEL=llama3-8b-instruct.Q4_K_M.gguf
      - GPU_LAYERS=-1
      - PRELOAD_MODEL=true
      - LOG_LEVEL=INFO
      - LOG_FILE=/app/logs/api.log
      - HOST=0.0.0.0
      - PORT=8000
      - API_KEY_REQUIRED=false
      # - API_KEY=your_api_key_here
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  # Nginx 서비스 (선택 사항)
  nginx:
    image: nginx:alpine
    container_name: llm-api-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - llm-api
    restart: unless-stopped

networks:
  default:
    name: llm-network